<ul class="breadcrumb">
    
    <?php foreach($this->pages as $page): ?>
        <?php if($page->isActive()): ?>
            <li>
                <?php echo $this->translate($page->getLabel()); ?>
            </li>
        <?php else: ?>
            <li>
                <a href="<?php echo $page->getHref(); ?>"><?php echo $this->translate($page->getLabel()); ?></a>
                <span class="divider"><?php echo $this->navigation()
                                                        ->breadcrumbs()
                                                        ->getSeparator(); ?></span>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
    
</ul>